services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: swayam
      POSTGRES_PASSWORD: paplu
      POSTGRES_DB: steguf
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
