services: 
  db: 
    image: postgres:15
    restart: always
    environment: 
      POSTGRES_USER: swayam
      POSTGRES_PASSWORD: paplu
      POSTGRES_DB: steguf
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
